### ISSUE TITLE
Directive overwrites inline css

### ISSUE THREAD

**Issue by carbotaniuman** [ajobi/vue-snip#5] opened 2021-04-04 04:26 UTC
Reproducer

```
<div v-snip="2" style="min-height: 3em;">
  Test
</div>
```

**Comment by ajobi** [comment] 2021-04-04 07:00
Hello and thanks for submitting the issue! This is expected with the current version as described here:
https://github.com/ajobi/vue-snip#element-style-attribute

It's possible for the directive to operate only on required style properties though and I think it could be added in the future. Do you have a use case where you cannot use classes?

**Comment by carbotaniuman** [comment] 2021-04-06 16:21
Oh, I didn't see that, moving that above the implementation notes might be a good idea. I was just trying to add some inline styling to a component, so no reason classes couldn't be used, but it was just a bit of a pain when debugging.

**Comment by ajobi** [comment] 2021-04-06 19:27
The issue is fixed with version 1.2.0.

**Closed by ajobi** 2021-04-06 19:27 UTC
Labels: enhancement
